/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hailu.kafka.model;
@org.apache.avro.specific.AvroGenerated
public enum Colors implements org.apache.avro.generic.GenericEnumSymbol<Colors> {
  RED, WHITE, BLUE, GREEN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Colors\",\"namespace\":\"com.hailu.kafka.model\",\"symbols\":[\"RED\",\"WHITE\",\"BLUE\",\"GREEN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
