/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hailu.kafka.model;
@org.apache.avro.specific.AvroGenerated
public enum DesignType implements org.apache.avro.generic.GenericEnumSymbol<DesignType> {
  SHORT_SLEEVE, LONG_SLEEVE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DesignType\",\"namespace\":\"com.hailu.kafka.model\",\"symbols\":[\"SHORT_SLEEVE\",\"LONG_SLEEVE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
