/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hailu.kafka.model;
@org.apache.avro.specific.AvroGenerated
public enum ProductType implements org.apache.avro.generic.GenericEnumSymbol<ProductType> {
  TSHIRT, BLOUSE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductType\",\"namespace\":\"com.hailu.kafka.model\",\"symbols\":[\"TSHIRT\",\"BLOUSE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
