/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hailu.kafka.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Product extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9144960326714123848L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Product\",\"namespace\":\"com.hailu.kafka.model\",\"fields\":[{\"name\":\"designType\",\"type\":{\"type\":\"enum\",\"name\":\"DesignType\",\"symbols\":[\"SHORT_SLEEVE\",\"LONG_SLEEVE\"]}},{\"name\":\"color\",\"type\":{\"type\":\"enum\",\"name\":\"Colors\",\"symbols\":[\"RED\",\"WHITE\",\"BLUE\",\"GREEN\"]}},{\"name\":\"productType\",\"type\":{\"type\":\"enum\",\"name\":\"ProductType\",\"symbols\":[\"TSHIRT\",\"BLOUSE\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Product> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Product> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Product> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Product> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Product> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Product to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Product from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Product instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Product fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.hailu.kafka.model.DesignType designType;
  private com.hailu.kafka.model.Colors color;
  private com.hailu.kafka.model.ProductType productType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Product() {}

  /**
   * All-args constructor.
   * @param designType The new value for designType
   * @param color The new value for color
   * @param productType The new value for productType
   */
  public Product(com.hailu.kafka.model.DesignType designType, com.hailu.kafka.model.Colors color, com.hailu.kafka.model.ProductType productType) {
    this.designType = designType;
    this.color = color;
    this.productType = productType;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return designType;
    case 1: return color;
    case 2: return productType;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: designType = (com.hailu.kafka.model.DesignType)value$; break;
    case 1: color = (com.hailu.kafka.model.Colors)value$; break;
    case 2: productType = (com.hailu.kafka.model.ProductType)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'designType' field.
   * @return The value of the 'designType' field.
   */
  public com.hailu.kafka.model.DesignType getDesignType() {
    return designType;
  }


  /**
   * Sets the value of the 'designType' field.
   * @param value the value to set.
   */
  public void setDesignType(com.hailu.kafka.model.DesignType value) {
    this.designType = value;
  }

  /**
   * Gets the value of the 'color' field.
   * @return The value of the 'color' field.
   */
  public com.hailu.kafka.model.Colors getColor() {
    return color;
  }


  /**
   * Sets the value of the 'color' field.
   * @param value the value to set.
   */
  public void setColor(com.hailu.kafka.model.Colors value) {
    this.color = value;
  }

  /**
   * Gets the value of the 'productType' field.
   * @return The value of the 'productType' field.
   */
  public com.hailu.kafka.model.ProductType getProductType() {
    return productType;
  }


  /**
   * Sets the value of the 'productType' field.
   * @param value the value to set.
   */
  public void setProductType(com.hailu.kafka.model.ProductType value) {
    this.productType = value;
  }

  /**
   * Creates a new Product RecordBuilder.
   * @return A new Product RecordBuilder
   */
  public static com.hailu.kafka.model.Product.Builder newBuilder() {
    return new com.hailu.kafka.model.Product.Builder();
  }

  /**
   * Creates a new Product RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Product RecordBuilder
   */
  public static com.hailu.kafka.model.Product.Builder newBuilder(com.hailu.kafka.model.Product.Builder other) {
    if (other == null) {
      return new com.hailu.kafka.model.Product.Builder();
    } else {
      return new com.hailu.kafka.model.Product.Builder(other);
    }
  }

  /**
   * Creates a new Product RecordBuilder by copying an existing Product instance.
   * @param other The existing instance to copy.
   * @return A new Product RecordBuilder
   */
  public static com.hailu.kafka.model.Product.Builder newBuilder(com.hailu.kafka.model.Product other) {
    if (other == null) {
      return new com.hailu.kafka.model.Product.Builder();
    } else {
      return new com.hailu.kafka.model.Product.Builder(other);
    }
  }

  /**
   * RecordBuilder for Product instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Product>
    implements org.apache.avro.data.RecordBuilder<Product> {

    private com.hailu.kafka.model.DesignType designType;
    private com.hailu.kafka.model.Colors color;
    private com.hailu.kafka.model.ProductType productType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.hailu.kafka.model.Product.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.designType)) {
        this.designType = data().deepCopy(fields()[0].schema(), other.designType);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.color)) {
        this.color = data().deepCopy(fields()[1].schema(), other.color);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.productType)) {
        this.productType = data().deepCopy(fields()[2].schema(), other.productType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Product instance
     * @param other The existing instance to copy.
     */
    private Builder(com.hailu.kafka.model.Product other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.designType)) {
        this.designType = data().deepCopy(fields()[0].schema(), other.designType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.color)) {
        this.color = data().deepCopy(fields()[1].schema(), other.color);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.productType)) {
        this.productType = data().deepCopy(fields()[2].schema(), other.productType);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'designType' field.
      * @return The value.
      */
    public com.hailu.kafka.model.DesignType getDesignType() {
      return designType;
    }


    /**
      * Sets the value of the 'designType' field.
      * @param value The value of 'designType'.
      * @return This builder.
      */
    public com.hailu.kafka.model.Product.Builder setDesignType(com.hailu.kafka.model.DesignType value) {
      validate(fields()[0], value);
      this.designType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'designType' field has been set.
      * @return True if the 'designType' field has been set, false otherwise.
      */
    public boolean hasDesignType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'designType' field.
      * @return This builder.
      */
    public com.hailu.kafka.model.Product.Builder clearDesignType() {
      designType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'color' field.
      * @return The value.
      */
    public com.hailu.kafka.model.Colors getColor() {
      return color;
    }


    /**
      * Sets the value of the 'color' field.
      * @param value The value of 'color'.
      * @return This builder.
      */
    public com.hailu.kafka.model.Product.Builder setColor(com.hailu.kafka.model.Colors value) {
      validate(fields()[1], value);
      this.color = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'color' field has been set.
      * @return True if the 'color' field has been set, false otherwise.
      */
    public boolean hasColor() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'color' field.
      * @return This builder.
      */
    public com.hailu.kafka.model.Product.Builder clearColor() {
      color = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'productType' field.
      * @return The value.
      */
    public com.hailu.kafka.model.ProductType getProductType() {
      return productType;
    }


    /**
      * Sets the value of the 'productType' field.
      * @param value The value of 'productType'.
      * @return This builder.
      */
    public com.hailu.kafka.model.Product.Builder setProductType(com.hailu.kafka.model.ProductType value) {
      validate(fields()[2], value);
      this.productType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'productType' field has been set.
      * @return True if the 'productType' field has been set, false otherwise.
      */
    public boolean hasProductType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'productType' field.
      * @return This builder.
      */
    public com.hailu.kafka.model.Product.Builder clearProductType() {
      productType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Product build() {
      try {
        Product record = new Product();
        record.designType = fieldSetFlags()[0] ? this.designType : (com.hailu.kafka.model.DesignType) defaultValue(fields()[0]);
        record.color = fieldSetFlags()[1] ? this.color : (com.hailu.kafka.model.Colors) defaultValue(fields()[1]);
        record.productType = fieldSetFlags()[2] ? this.productType : (com.hailu.kafka.model.ProductType) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Product>
    WRITER$ = (org.apache.avro.io.DatumWriter<Product>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Product>
    READER$ = (org.apache.avro.io.DatumReader<Product>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.designType.ordinal());

    out.writeEnum(this.color.ordinal());

    out.writeEnum(this.productType.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.designType = com.hailu.kafka.model.DesignType.values()[in.readEnum()];

      this.color = com.hailu.kafka.model.Colors.values()[in.readEnum()];

      this.productType = com.hailu.kafka.model.ProductType.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.designType = com.hailu.kafka.model.DesignType.values()[in.readEnum()];
          break;

        case 1:
          this.color = com.hailu.kafka.model.Colors.values()[in.readEnum()];
          break;

        case 2:
          this.productType = com.hailu.kafka.model.ProductType.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










