/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hailu.kafka.model;
@org.apache.avro.specific.AvroGenerated
public enum UserId implements org.apache.avro.generic.GenericEnumSymbol<UserId> {
  USER_ZERO, USER_ONE, USER_TWO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UserId\",\"namespace\":\"com.hailu.kafka.model\",\"symbols\":[\"USER_ZERO\",\"USER_ONE\",\"USER_TWO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
